spring.application.name=todoapp
spring.main.web-application-type=servlet
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/todoapp
spring.datasource.username=todoapp_user
spring.datasource.password=todoapp78

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
